apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: financial-services
  labels:
    app: auth-service
    service: auth-service
    version: v1
    component: authentication
    tier: critical
    qos-class: guaranteed
    compliance: sox-pci-gdpr
    environment: production
    team: platform-security
    cost-center: infrastructure
  annotations:
    # Monitoring and observability
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/scheme: "http"
    
    # Service mesh integration
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    
    # Security annotations
    security.alpha.kubernetes.io/audit-level: "RequestResponse"
    compliance.kubernetes.io/sox-required: "true"
    compliance.kubernetes.io/pci-dss: "true"
    compliance.kubernetes.io/gdpr: "true"
    
    # Documentation and support
    service.kubernetes.io/description: "Authentication and authorization service for financial services platform"
    service.kubernetes.io/owner: "platform-security-team"
    service.kubernetes.io/contact: "security@financialplatform.com"
    service.kubernetes.io/documentation: "https://docs.financialplatform.com/auth-service"
    service.kubernetes.io/runbook: "https://runbooks.financialplatform.com/auth-service"
    
    # Change management
    deployment.kubernetes.io/revision: "1"
    deployment.kubernetes.io/created-by: "platform-team"
    deployment.kubernetes.io/last-updated: "2025-01-01T00:00:00Z"
    
    # Service discovery and load balancing
    service.kubernetes.io/load-balancer-source-ranges: "10.0.0.0/8"
    service.kubernetes.io/session-affinity: "ClientIP"
    service.kubernetes.io/session-affinity-timeout: "86400"
spec:
  type: ClusterIP
  selector:
    app: auth-service
    component: authentication
    version: v1
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: actuator
      protocol: TCP
      port: 8081
      targetPort: 8081
    - name: metrics
      protocol: TCP
      port: 9090
      targetPort: 9090
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 86400
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster