package com.ufs.compliance.dto;

import lombok.Data; // v1.18.30
import lombok.Builder; // v1.18.30
import java.util.List; // Java 17
import java.time.LocalDateTime; // Java 17

/**
 * Data Transfer Object (DTO) representing the response of a compliance check operation.
 * 
 * This class encapsulates the results of various compliance verifications, such as AML 
 * (Anti-Money Laundering) and sanctions screening, for a specific customer or transaction.
 * It serves as the output structure for the regulatory compliance automation feature (F-003)
 * and carries the results of KYC/AML checks performed during customer onboarding or 
 * transaction processing (F-004-RQ-002).
 * 
 * The DTO is designed to support:
 * - Real-time compliance monitoring and reporting
 * - Unified risk scoring across multiple regulatory frameworks
 * - Complete audit trails for all compliance activities
 * - Customer identification programme (CIP) and customer due diligence (CDD) processes
 * 
 * @author UFS Compliance Service
 * @version 1.0
 * @since 2025-01-01
 */
@Data
@Builder
public class ComplianceCheckResponse {

    /**
     * Unique identifier for the compliance check operation.
     * 
     * This ID is generated by the compliance service and can be used to track
     * the specific compliance check instance for audit purposes and correlation
     * with other system operations.
     * 
     * Format: UUID string representation
     * Example: "cc-12345678-90ab-cdef-1234-567890abcdef"
     */
    private String checkId;

    /**
     * Unique identifier of the customer being subjected to the compliance check.
     * 
     * This corresponds to the customer's primary identifier in the unified data
     * integration platform and enables correlation with customer profiles across
     * all touchpoints and systems.
     * 
     * Format: Customer ID as defined by the customer management system
     * Example: "CUST-001234567"
     */
    private String customerId;

    /**
     * Unique identifier of the transaction being checked for compliance, if applicable.
     * 
     * This field is populated when the compliance check is triggered by a specific
     * transaction and enables traceability between compliance results and financial
     * operations for regulatory reporting purposes.
     * 
     * Format: Transaction ID as defined by the transaction processing system
     * Example: "TXN-987654321" or null for customer-level checks
     */
    private String transactionId;

    /**
     * Overall status of the compliance check operation.
     * 
     * Represents the aggregate result of all compliance verifications performed.
     * This status determines whether the customer or transaction can proceed or
     * requires manual review or rejection.
     * 
     * Possible values:
     * - "PASSED": All compliance checks passed successfully
     * - "FAILED": One or more compliance checks failed
     * - "PENDING": Manual review required or awaiting external verification
     * - "ERROR": System error occurred during compliance checking
     * - "ESCALATED": Flagged for senior compliance officer review
     */
    private String status;

    /**
     * Timestamp indicating when the compliance check was performed.
     * 
     * This timestamp is critical for audit trails and regulatory reporting,
     * ensuring compliance with record-keeping requirements and enabling
     * temporal analysis of compliance patterns.
     * 
     * Format: ISO 8601 datetime in system timezone
     * Precision: Milliseconds for accurate ordering of compliance events
     */
    private LocalDateTime timestamp;

    /**
     * Specific status of the Anti-Money Laundering (AML) check component.
     * 
     * AML checks are mandatory under Bank Secrecy Act (BSA) requirements and
     * international KYC/AML rules. This field provides granular visibility
     * into the AML verification results independent of other compliance checks.
     * 
     * Possible values:
     * - "CLEARED": No AML concerns identified
     * - "FLAGGED": Potential AML risk detected, requires review
     * - "BLOCKED": High AML risk, transaction/customer blocked
     * - "INCONCLUSIVE": Insufficient data for AML determination
     * - "EXEMPTED": AML check exempted due to customer category/threshold
     */
    private String amlCheckStatus;

    /**
     * Specific status of the sanctions screening check component.
     * 
     * Sanctions screening is performed against watchlists worldwide including
     * OFAC, EU, UN, and jurisdiction-specific sanctions lists. This ensures
     * compliance with international sanctions regimes and prevents prohibited
     * transactions.
     * 
     * Possible values:
     * - "CLEARED": No sanctions matches found
     * - "POTENTIAL_MATCH": Possible sanctions list match, requires review
     * - "CONFIRMED_MATCH": Confirmed sanctions list match, blocked
     * - "FALSE_POSITIVE": Initial match cleared after review
     * - "SCREENING_ERROR": Technical error in sanctions screening process
     */
    private String sanctionsCheckStatus;

    /**
     * List of specific compliance rules that were violated during the check.
     * 
     * This field provides detailed information about which regulatory or
     * business rules were triggered, enabling precise remediation actions
     * and supporting regulatory reporting requirements. Empty list indicates
     * no rule violations were detected.
     * 
     * Examples:
     * - "AML_SUSPICIOUS_PATTERN_DETECTED"
     * - "SANCTIONS_PARTIAL_NAME_MATCH"
     * - "KYC_INCOMPLETE_DOCUMENTATION"
     * - "CDD_ENHANCED_DUE_DILIGENCE_REQUIRED"
     * - "PEP_POLITICALLY_EXPOSED_PERSON"
     * - "HIGH_RISK_JURISDICTION"
     */
    private List<String> violatedRules;

    /**
     * Human-readable summary of the compliance check results.
     * 
     * This field provides a concise narrative description of the compliance
     * check outcome, including key findings and recommended actions. It serves
     * as a quick reference for compliance officers and can be included in
     * customer communications or regulatory reports.
     * 
     * The summary should be professional, clear, and actionable, supporting
     * both automated processing and human decision-making in the compliance
     * workflow.
     * 
     * Example: "Customer passed all compliance checks. AML screening cleared 
     * with no suspicious patterns detected. Sanctions screening returned no 
     * matches. Account approved for standard processing."
     */
    private String summary;
}