/**
 * Compliance Data Models
 * 
 * This file defines the TypeScript interfaces for compliance-related features
 * supporting regulatory compliance automation, digital customer onboarding,
 * and the compliance control center interface.
 * 
 * Supports requirements:
 * - F-003: Regulatory Compliance Automation
 * - F-004: Digital Customer Onboarding
 * - F-015: Compliance Control Center
 * 
 * @version 1.0.0
 * @author Unified Financial Services Platform
 */

/**
 * Represents a single regulatory rule within the compliance framework.
 * 
 * This interface supports automated regulatory compliance monitoring and
 * real-time policy updates as required by F-003 specifications.
 * 
 * The regulatory rule system handles multiple frameworks including:
 * - PSD3 (Payment Services Directive 3)
 * - PSR (Payment Services Regulation)
 * - Basel III/IV reforms
 * - FRTB (Fundamental Review of the Trading Book)
 * - GDPR, SOX, PCI DSS compliance
 * 
 * @interface RegulatoryRule
 */
export interface RegulatoryRule {
  /**
   * Unique identifier for the regulatory rule.
   * Used for tracking and referencing across compliance systems.
   * 
   * @type {string}
   * @example "REG-001-PSD3-2025"
   */
  id: string;

  /**
   * Human-readable name of the regulatory rule.
   * Should be descriptive and aligned with regulatory framework terminology.
   * 
   * @type {string}
   * @example "PSD3 Strong Customer Authentication"
   */
  name: string;

  /**
   * Detailed description of the regulatory rule.
   * Includes implementation requirements and compliance criteria.
   * 
   * @type {string}
   * @example "Implementation of strong customer authentication requirements under PSD3 framework"
   */
  description: string;

  /**
   * Legal jurisdiction where the regulatory rule applies.
   * Supports multi-jurisdictional compliance requirements.
   * 
   * @type {string}
   * @example "EU", "US", "UK", "GLOBAL"
   */
  jurisdiction: string;

  /**
   * Regulatory framework or standard that the rule belongs to.
   * Enables categorization and framework-specific compliance monitoring.
   * 
   * @type {string}
   * @example "PSD3", "Basel III", "GDPR", "SOX", "PCI DSS"
   */
  framework: string;

  /**
   * Current status of the regulatory rule.
   * Supports automated policy lifecycle management.
   * 
   * - ACTIVE: Rule is currently in effect and being enforced
   * - INACTIVE: Rule is not currently active or has been superseded
   * - PENDING: Rule is scheduled for activation or under review
   * 
   * @type {'ACTIVE' | 'INACTIVE' | 'PENDING'}
   */
  status: 'ACTIVE' | 'INACTIVE' | 'PENDING';

  /**
   * Timestamp of the last update to the regulatory rule.
   * Supports the 24-hour automated policy update requirement.
   * 
   * @type {string}
   * @format ISO 8601 datetime string
   * @example "2025-01-15T14:30:00.000Z"
   */
  lastUpdated: string;
}

/**
 * Represents a compliance report generated by the system.
 * 
 * This interface supports automated compliance reporting with high automation
 * levels (80-95%) as specified in the technical requirements.
 * 
 * Supports compliance frameworks including:
 * - SOX Compliance (Quarterly reporting)
 * - PCI DSS (Annual reporting)
 * - GDPR (On-demand reporting)
 * - Basel III (Monthly reporting)
 * 
 * @interface ComplianceReport
 */
export interface ComplianceReport {
  /**
   * Unique identifier for the compliance report.
   * Used for tracking and audit trail purposes.
   * 
   * @type {string}
   * @example "RPT-SOX-2025-Q1-001"
   */
  id: string;

  /**
   * Descriptive name of the compliance report.
   * Should clearly indicate the report type and scope.
   * 
   * @type {string}
   * @example "SOX Quarterly Compliance Report Q1 2025"
   */
  name: string;

  /**
   * Detailed description of the report contents and scope.
   * Includes information about data sources and compliance frameworks covered.
   * 
   * @type {string}
   * @example "Quarterly SOX compliance assessment covering financial controls and audit requirements"
   */
  description: string;

  /**
   * Timestamp when the report was generated.
   * Supports audit trail and compliance timeline tracking.
   * 
   * @type {string}
   * @format ISO 8601 datetime string
   * @example "2025-03-31T23:59:59.999Z"
   */
  generatedAt: string;

  /**
   * Current status of the compliance report.
   * Supports report lifecycle management and approval workflows.
   * 
   * - DRAFT: Report is being prepared or under review
   * - FINAL: Report has been approved and finalized
   * - ARCHIVED: Report has been archived for historical reference
   * 
   * @type {'DRAFT' | 'FINAL' | 'ARCHIVED'}
   */
  status: 'DRAFT' | 'FINAL' | 'ARCHIVED';

  /**
   * URL or file path to access the compliance report.
   * Supports secure document storage and retrieval.
   * 
   * @type {string}
   * @example "https://secure-storage.company.com/compliance/reports/SOX-2025-Q1.pdf"
   */
  url: string;
}

/**
 * Represents the status of an Anti-Money Laundering (AML) check for a customer.
 * 
 * This interface supports digital customer onboarding (F-004) with KYC/AML
 * compliance checks as required by financial regulations.
 * 
 * Supports compliance with:
 * - Bank Secrecy Act (BSA) requirements
 * - FinCEN database integration
 * - International KYC/AML rules
 * - Watchlist screening against AML databases
 * 
 * @interface AmlCheck
 */
export interface AmlCheck {
  /**
   * Unique identifier for the AML check.
   * Used for tracking and audit purposes.
   * 
   * @type {string}
   * @example "AML-CHK-2025-001234"
   */
  id: string;

  /**
   * Unique identifier of the customer being checked.
   * Links the AML check to the customer profile.
   * 
   * @type {string}
   * @example "CUST-2025-567890"
   */
  customerId: string;

  /**
   * Current status of the AML check.
   * Supports automated risk assessment and escalation workflows.
   * 
   * - PENDING: Check is in progress or awaiting review
   * - CLEARED: Customer has passed AML screening
   * - FAILED: Customer has failed AML screening
   * - ESCALATED: Check requires manual review or investigation
   * 
   * @type {'PENDING' | 'CLEARED' | 'FAILED' | 'ESCALATED'}
   */
  status: 'PENDING' | 'CLEARED' | 'FAILED' | 'ESCALATED';

  /**
   * Timestamp when the AML check was performed.
   * Supports audit trail and compliance timeline tracking.
   * 
   * @type {string}
   * @format ISO 8601 datetime string
   * @example "2025-01-15T10:30:00.000Z"
   */
  checkedAt: string;

  /**
   * Risk level assessment from the AML check.
   * Supports risk-based onboarding and enhanced due diligence requirements.
   * 
   * - LOW: Minimal risk, standard onboarding procedures
   * - MEDIUM: Moderate risk, additional verification may be required
   * - HIGH: High risk, enhanced due diligence and manual review required
   * 
   * @type {'LOW' | 'MEDIUM' | 'HIGH'}
   */
  riskLevel: 'LOW' | 'MEDIUM' | 'HIGH';

  /**
   * Detailed information about the AML check results.
   * Includes screening results, risk factors, and recommendations.
   * 
   * @type {string}
   * @example "Customer cleared against all AML watchlists. No adverse media findings. Standard risk profile."
   */
  details: string;
}

/**
 * Represents a generic compliance check performed on an entity like a customer or transaction.
 * 
 * This interface supports various compliance checks beyond AML, including:
 * - Identity verification checks
 * - Document validation checks
 * - Biometric authentication checks
 * - Transaction monitoring checks
 * - Regulatory screening checks
 * 
 * Supports F-004 digital onboarding and F-003 compliance automation requirements.
 * 
 * @interface ComplianceCheck
 */
export interface ComplianceCheck {
  /**
   * Unique identifier for the compliance check.
   * Used for tracking and audit trail purposes.
   * 
   * @type {string}
   * @example "CHK-KYC-2025-001234"
   */
  id: string;

  /**
   * Type of compliance check being performed.
   * Enables categorization and specific processing logic.
   * 
   * @type {string}
   * @example "IDENTITY_VERIFICATION", "DOCUMENT_VALIDATION", "BIOMETRIC_AUTH", "TRANSACTION_MONITORING"
   */
  checkType: string;

  /**
   * Current status of the compliance check.
   * Supports automated processing and decision workflows.
   * 
   * - PENDING: Check is in progress or awaiting processing
   * - PASSED: Check has been completed successfully
   * - FAILED: Check has failed compliance requirements
   * 
   * @type {'PENDING' | 'PASSED' | 'FAILED'}
   */
  status: 'PENDING' | 'PASSED' | 'FAILED';

  /**
   * Detailed results and information about the compliance check.
   * Includes specific findings, validation results, and recommendations.
   * 
   * @type {string}
   * @example "Identity document verified successfully. Document authenticity confirmed. Address validation passed."
   */
  details: string;

  /**
   * Timestamp when the compliance check was performed.
   * Supports audit trail and compliance timeline requirements.
   * 
   * @type {string}
   * @format ISO 8601 datetime string
   * @example "2025-01-15T10:30:00.000Z"
   */
  timestamp: string;

  /**
   * Unique identifier of the entity being checked.
   * Links the compliance check to the relevant entity (customer, transaction, etc.).
   * 
   * @type {string}
   * @example "CUST-2025-567890", "TXN-2025-123456"
   */
  entityId: string;

  /**
   * Type of entity being checked.
   * Enables entity-specific processing and validation logic.
   * 
   * - CUSTOMER: Compliance check performed on a customer
   * - TRANSACTION: Compliance check performed on a transaction
   * 
   * @type {'CUSTOMER' | 'TRANSACTION'}
   */
  entityType: 'CUSTOMER' | 'TRANSACTION';
}